[general]
name = "trimul-gpumode"
# license is best-effort, happy to update if it doesn't match the upstream license
license = "Apache-2.0"
version = 1
backends = [
    "cuda",
    "rocm",
    "xpu",
]


[general.hub]
repo-id = "kernels-community/trimul-gpumode"

[kernel]
