[general]
name = "triton-kernels"
# license is best-effort, happy to update if it doesn't match the upstream license
license = "Apache-2.0"
backends = [
    "cuda",
]

[general.hub]
repo-id = "kernels-community/triton-kernels"
