# Regenerates build.toml's kernel sections from the files on disk.
#
# kernel-builder requires static `src` lists (they define both the Nix source
# fileset and the CMake sources), while NATTEN's kernel instantiations are
# autogenerated. Run this after `scripts/regen.sh` so the lists stay in sync
# with the autogen output. Usage:
#
#   python3 scripts/generate_build_toml.py

import os
import sys
from pathlib import Path

KERNEL_DIR = Path(__file__).resolve().parent.parent

HEADER = """\
[general]
name = "natten"
version = 1
edition = 5
license = "MIT"
upstream = "https://github.com/SHI-Labs/NATTEN"
backends = ["cuda"]

[general.hub]
repo-id = "kernels-community/natten"

[torch]
src = ["torch-ext/torch_binding.cpp"]
include = ["csrc/include"]
"""

COMMON_CUDA_FLAGS = [
    "-O3",
    "-std=c++17",
    "--expt-relaxed-constexpr",
    "--extended-lambda",
    "--use_fast_math",
    "--ftemplate-backtrace-limit=0",
    "-Xfatbin=-compress-all",
    "-DNDEBUG",
    "-DNATTEN_WITH_CUTLASS",
    "-DCUTLASS_ENABLE_TENSOR_CORE_MMA=1",
]

DEPENDS = ["torch", "cutlass_4_5"]
INCLUDE = ["csrc/include", "csrc/autogen/include"]

# Upstream compiles hopper (90) and blackwell (100/103) kernels with
# arch-specific ("a") targets; see setup.py's arch_list_to_cmake_tags.
# SM103 is not in kernel-builder's supported arch list yet, so Blackwell
# Ultra (B300) is not covered. Blackwell kernels need CUDA >= 12.8; the
# section is skipped (via cuda-minver) on older toolkits, and the natten.h
# CUDART_VERSION gate turns the static dispatchers into stubs to match.
SECTIONS = [
    {
        "name": "natten",
        "capabilities": ["7.0", "7.5", "8.0", "8.6", "8.9", "9.0", "10.0", "12.0"],
        "minver": None,
        "extra_flags": [],
        "autogen_dirs": ["reference", "fna", "fmha"],
        "static_src": True,
    },
    {
        "name": "natten_hopper",
        "capabilities": ["9.0a"],
        "minver": None,
        "extra_flags": ["-DNATTEN_WITH_HOPPER_FNA=1"],
        "autogen_dirs": [
            "hopper_fna",
            "hopper_fna_bwd",
            "hopper_fmha",
            "hopper_fmha_bwd",
        ],
        "static_src": False,
    },
    {
        "name": "natten_blackwell",
        "capabilities": ["10.0a"],
        "minver": "12.8",
        "extra_flags": ["-DNATTEN_WITH_BLACKWELL_FNA=1"],
        "autogen_dirs": [
            "blackwell_fna",
            "blackwell_fna_bwd",
            "blackwell_fmha",
            "blackwell_fmha_bwd",
        ],
        "static_src": False,
    },
]


def rel_files(subdir: str, exts=(".h", ".hpp", ".cuh", ".cu", ".cpp")) -> list:
    root = KERNEL_DIR / subdir
    if not root.is_dir():
        sys.exit(f"error: {root} does not exist; run scripts/regen.sh first")
    out = []
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix in exts:
            out.append(str(path.relative_to(KERNEL_DIR)))
    return out


def toml_list(key: str, values: list, indent: str = "") -> str:
    lines = [f"{indent}{key} = ["]
    for v in values:
        lines.append(f'{indent}    "{v}",')
    lines.append(f"{indent}]")
    return "\n".join(lines)


def main() -> None:
    parts = [HEADER]

    for section in SECTIONS:
        src = []
        if section["static_src"]:
            # All shared headers ride along with the core section; every
            # section adds csrc/include and csrc/autogen/include to its
            # include path.
            src += rel_files("csrc/include")
            src += rel_files("csrc/src")
        for autogen_dir in section["autogen_dirs"]:
            src += rel_files(f"csrc/autogen/include/natten_autogen/cuda/{autogen_dir}")
            src += rel_files(f"csrc/autogen/src/cuda/{autogen_dir}")

        lines = [f"[kernel.{section['name']}]"]
        lines.append('backend = "cuda"')
        if section["minver"]:
            lines.append(f'cuda-minver = "{section["minver"]}"')
        lines.append(toml_list("cuda-capabilities", section["capabilities"]))
        lines.append(
            toml_list("cuda-flags", COMMON_CUDA_FLAGS + section["extra_flags"])
        )
        lines.append(toml_list("depends", DEPENDS))
        lines.append(toml_list("include", INCLUDE))
        lines.append(toml_list("src", src))
        parts.append("\n".join(lines) + "\n")

    (KERNEL_DIR / "build.toml").write_text("\n".join(parts))
    print(f"wrote {KERNEL_DIR / 'build.toml'}")


if __name__ == "__main__":
    main()
