[general]
name = "activation"
version = 1
license = "Apache-2.0"
backends = [
    "cuda",
    "metal",
]

[general.hub]
repo-id = "kernels-community/activation"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[torch.stable-abi]
cuda = "2.11"

[kernel.activation_metal]
backend = "metal"
depends = ["torch"]
src = [
    "activation_metal/activation.mm",
    "activation_metal/activation.metal",
]

[kernel.activation]
backend = "cuda"
depends = ["torch"]
src = [
    "activation/activation_kernels.cu",
    "activation/cuda_compat.h",
    "activation/dispatch_utils.h",
]
