[general]
name = "einops"
version = 1
license = "MIT"
edition = 5
upstream = "https://github.com/arogozhnikov/einops.git"
backends = [
    "cpu",
    "cuda",
    "metal",
    "rocm",
    "xpu",
]

[general.hub]
repo-id = "kernels-community/einops"

[torch-noarch]

[kernel]
